### ISSUE TITLE
Error: Cannot find module '../../../../../images'

### ISSUE THREAD

**Issue by layinka** [stellarterm/stellarterm#808]
I am getting this error when i try to run the project ( npm start )

```
Error: Cannot find module '../../../../images' from '/var/www/sdex/src/components/Session/LoginPage/TrezorBody'
    at /var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Cannot find module '../../../../images' from '/var/www/sdex/src/components/Session/SessionContent/SepTransactions'
    at /var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Cannot find module './../../../../images' from '/var/www/sdex/src/components/GlobalModal/Sep7Modals/TransactionAuthorBlock'
    at /var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
Error: Cannot find module '../../../../../images' from '/var/www/sdex/src/components/Session/LoginPage/Common/HardwareWalletLoginLink'
    at /var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /var/www/sdex/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Comment by nash81** [comment]
I have the same issue were you able to resolve it?
